import re

with open('src/pages/SummaryReports.tsx', 'r') as f:
    content = f.read()

# Insert pagination logic before the return statement
pagination_logic = """
  const ROWS_PAGE_1 = 7;
  const ROWS_PAGE_N = 12;

  const pages: CaseRecord[][] = [];
  let currentIndex = 0;
  
  if (activeCases.length === 0) {
    pages.push([]);
  } else {
    const page1 = activeCases.slice(0, ROWS_PAGE_1);
    pages.push(page1);
    currentIndex += ROWS_PAGE_1;
    
    while (currentIndex < activeCases.length) {
      pages.push(activeCases.slice(currentIndex, currentIndex + ROWS_PAGE_N));
      currentIndex += ROWS_PAGE_N;
    }
  }

  const lastPageCapacity = pages.length === 1 ? ROWS_PAGE_1 : ROWS_PAGE_N;
  const lastPageRows = pages[pages.length - 1].length;
  const needsExtraPage = activeCases.length > 0 && (lastPageCapacity - lastPageRows) < 4;
  const totalPagesCount = pages.length + (needsExtraPage ? 1 : 0);

  const renderTableHeader = () => (
    <thead>
      <tr className="border-b border-gray-200 text-gray-600 font-bold uppercase text-[11px] tracking-wider font-sans">
        <th className="py-2 pr-2 w-8">#</th>
        <th className="py-2 pr-2">Incident Date</th>
        <th className="py-2 pr-2">Student</th>
        <th className="py-2 pr-2">Class</th>
        <th className="py-2 pr-2">Adviser</th>
        <th className="py-2 pr-2">Type</th>
        <th className="py-2 pr-2 max-w-[140px]">Description</th>
        <th className="py-2 pr-2 max-w-[120px]">Sanction</th>
        <th className="py-2 text-right">Status</th>
      </tr>
    </thead>
  );

  const renderSmallHeader = () => (
    <div className="flex justify-between items-end border-b pb-3 mb-6 font-sans">
      <div>
        <h2 className="m-0 text-[13px] font-black uppercase tracking-wider text-black">Laguna College Guidance Office</h2>
        <p className="m-0 mt-0.5 text-[10px] font-bold text-gray-600">
          {periodType === "monthly" ? "Monthly Disciplinary Case Report" : "Yearly Disciplinary Case Report"}
        </p>
      </div>
      <div className="text-right">
        <p className="m-0 text-[10px] text-gray-500">
          {periodType === "monthly" ? selectedMonth : selectedYear}
        </p>
        <p className="m-0 mt-0.5 text-[9px] text-gray-400 uppercase font-bold tracking-widest">
          Case List (Continued)
        </p>
      </div>
    </div>
  );

  const renderPageFooter = (currentPage: number, totalPages: number) => (
    <div className="absolute bottom-8 left-12 right-12 flex justify-between items-end text-[10px] text-gray-400 font-sans border-t pt-4 bg-white">
      <div className="flex flex-col">
        <span className="font-bold">Generated by LCGO Guidance Information System</span>
        <span>Confidential Student Record</span>
      </div>
      <div className="font-bold">Page {currentPage} of {totalPages}</div>
    </div>
  );

  const renderClosingBlock = () => (
    <div className="mt-8 font-sans">
      <div className="border-t border-gray-300 pt-4 mb-8 text-center text-[10px] font-bold text-gray-500 uppercase tracking-widest">
        End of Report
      </div>
      
      <div className="mb-12 text-sm text-center">
        <span className="font-bold text-gray-600 mr-4">Total Cases:</span>
        <span className="font-bold text-black text-lg">{stats.total}</span>
      </div>
      
      {includes.signature && (
        <div className="flex justify-between w-3/4 mx-auto mt-16">
          <div className="flex flex-col items-center w-56 text-center">
            <div className="border-b border-gray-800 w-full mb-2"></div>
            <div className="font-bold text-sm">Guidance Counselor</div>
            <div className="text-xs text-gray-500 mt-1">Prepared by</div>
          </div>
          <div className="flex flex-col items-center w-56 text-center">
            <div className="border-b border-gray-800 w-full mb-2"></div>
            <div className="font-bold text-sm">School Principal</div>
            <div className="text-xs text-gray-500 mt-1">Noted by</div>
          </div>
        </div>
      )}
    </div>
  );

"""

# find "return (" inside SummaryReports function body
return_idx = content.find("  return (\n    <div className=")
content = content[:return_idx] + pagination_logic + content[return_idx:]

# Now replace the ref={reportRef} part with the chunked mapping
report_ref_start = content.find('<div \n              ref={reportRef}')
if report_ref_start == -1:
    report_ref_start = content.find('<div\n              ref={reportRef}')
if report_ref_start == -1:
    report_ref_start = content.find('<div ref={reportRef}')

report_ref_end = content.find('</div>\n          </div>\n        </div>\n      </div>', report_ref_start)

new_report_ref_content = """<div ref={reportRef} className="flex flex-col gap-8 print:gap-0 bg-transparent print:bg-white w-[297mm] origin-top">
              {pages.map((pageRows, index) => {
                const isFirstPage = index === 0;
                const isLastPageChunk = index === pages.length - 1;
                const globalStartIndex = isFirstPage ? 0 : ROWS_PAGE_1 + (index - 1) * ROWS_PAGE_N;

                return (
                  <div key={index} className="bg-white shadow-md print:shadow-none w-[297mm] h-[210mm] px-12 py-8 text-gray-800 font-serif relative" style={{ pageBreakAfter: 'always' }}>
                    
                    {isFirstPage ? (
                      <>
                        <div className="grid grid-cols-[84px_1fr_84px] items-center gap-4 mb-4 font-sans">
                          <img src={lcOfficialLogo} alt="Laguna College Logo" className="w-[72px] h-[72px] object-contain justify-self-start" />
                          <div className="text-center text-black" style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}>
                            <h2 className="m-0 text-[15px] leading-[18px] font-black uppercase tracking-[0.02em] text-black">LAGUNA COLLEGE</h2>
                            <p className="m-0 mt-0.5 text-[11px] leading-[13px] font-bold text-black">San Pablo City</p>
                            <p className="m-0 mt-0.5 text-[18px] leading-[21px] font-black text-black">Guidance Office</p>
                          </div>
                          <img src={guidanceLogo} alt="Guidance Office Logo" className="w-[72px] h-[72px] object-contain justify-self-end" />
                        </div>
                        
                        <div className="h-0.5 w-full bg-primary mb-5"></div>

                        <div className="text-center mb-6">
                          <h1 className="text-base font-bold uppercase tracking-wider mb-0.5 font-sans">
                            {periodType === "monthly" ? "Monthly Report on Disciplinary Cases" : "Yearly Report on Disciplinary Cases"}
                          </h1>
                          <p className="text-xs text-gray-500 font-sans">Official Disciplinary Case Report</p>
                        </div>

                        <div className="grid grid-cols-2 gap-x-8 gap-y-1.5 mb-6 text-xs w-3/4 mx-auto font-sans text-left">
                          {periodType === "monthly" ? (
                            <div className="flex">
                              <span className="w-32 text-gray-500">Reporting period</span>
                              <span className="font-medium">{selectedMonth}</span>
                            </div>
                          ) : (
                            <div className="flex">
                              <span className="w-32 text-gray-500">Academic year</span>
                              <span className="font-medium">{selectedYear.replace('A.Y. ', '')}</span>
                            </div>
                          )}
                          <div className="flex">
                            <span className="w-32 text-gray-500">Scope</span>
                            <span className="font-medium">{scope === 'all' ? 'All year levels' : selectedGrade}</span>
                          </div>
                          <div className="flex">
                            <span className="w-32 text-gray-500">Role filter</span>
                            <span className="font-medium">{selectedRole === 'all' ? 'All roles' : selectedRole}</span>
                          </div>
                          <div className="flex">
                            <span className="w-32 text-gray-500">Status filter</span>
                            <span className="font-medium">{selectedStatus === 'all' ? 'All statuses' : selectedStatus}</span>
                          </div>
                          <div className="flex">
                            <span className="w-32 text-gray-500">Date generated</span>
                            <span className="font-medium">
                              {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                            </span>
                          </div>
                        </div>

                        {includes.summary && (
                          <div className="mb-6 font-sans">
                            <h3 className="text-[10px] font-bold text-primary uppercase tracking-wider mb-2 border-b pb-1">Summary</h3>
                            <div className="grid grid-cols-4 gap-4">
                              <div className="border border-gray-200 rounded-lg py-2 px-3 flex justify-between">
                                <span className="text-[9px] leading-5 text-gray-500 font-bold uppercase tracking-wider">Total Cases</span>
                                <span className="text-base leading-5 font-bold text-gray-900">{stats.total}</span>
                              </div>
                              <div className="border border-gray-200 rounded-lg py-2 px-3 flex justify-between">
                                <span className="text-[9px] leading-5 text-gray-500 font-bold uppercase tracking-wider">Pending Cases</span>
                                <span className="text-base leading-5 font-bold text-gray-900">{stats.pending}</span>
                              </div>
                              <div className="border border-gray-200 rounded-lg py-2 px-3 flex justify-between">
                                <span className="text-[9px] leading-5 text-gray-500 font-bold uppercase tracking-wider">Resolved Cases</span>
                                <span className="text-base leading-5 font-bold text-gray-900">{stats.resolved}</span>
                              </div>
                              <div className="border border-gray-200 rounded-lg py-2 px-3 flex justify-between">
                                <span className="text-[9px] leading-5 text-gray-500 font-bold uppercase tracking-wider">Reprimand Cases</span>
                                <span className="text-base leading-5 font-bold text-gray-900">{stats.reprimand}</span>
                              </div>
                            </div>
                          </div>
                        )}
                        <h3 className="text-[12px] font-bold text-primary uppercase tracking-wider mb-2 border-b pb-1 font-sans">Case List</h3>
                      </>
                    ) : (
                      renderSmallHeader()
                    )}

                    {/* Table chunk for this page */}
                    <div className="w-full">
                      <table className="w-full text-left border-collapse min-w-full">
                        {renderTableHeader()}
                        <tbody>
                          {pageRows.length > 0 ? pageRows.map((c, i) => {
                            const students = parseStudents(c.students);
                            let studentName = "";
                            let studentGrade = "";
                            let studentAdviser = c.adviser || "—";
                            
                            if (students.length > 0) {
                              const s = students[0];
                              studentName = `${s.lastName}, ${s.firstName}${s.middleInitial ? ` ${s.middleInitial}.` : ""}`;
                              studentGrade = `${s.level.replace('Grade ', '')}-${s.section}`;
                              studentAdviser = s.adviser || c.adviser || "—";
                            } else {
                              studentName = `${c.last_name}, ${c.first_name}${c.middle_initial ? ` ${c.middle_initial}.` : ""}`;
                              studentGrade = `${c.level.replace('Grade ', '')}-${c.section}`;
                              studentAdviser = c.adviser || "—";
                            }
                            
                            return (
                              <tr key={i} className="border-b border-gray-100 last:border-0 text-[12px] even:bg-[#FAFAFA]" style={{ pageBreakInside: 'avoid' }}>
                                <td className="py-3 pr-2 pl-2 text-gray-500 font-sans font-bold">{globalStartIndex + i + 1}</td>
                                <td className="py-3 pr-2 text-gray-600 font-sans whitespace-nowrap">{formatDate(c.date)}</td>
                                <td className="py-3 pr-2 font-medium text-gray-900 font-sans">{studentName}</td>
                                <td className="py-3 pr-2 text-gray-600 font-sans whitespace-nowrap">{studentGrade}</td>
                                <td className="py-3 pr-2 text-gray-600 font-sans">{studentAdviser}</td>
                                <td className="py-3 pr-2 text-gray-600 font-sans">{c.case}</td>
                                <td className="py-3 pr-2 text-gray-600 font-sans max-w-[140px] break-words">{c.description || "—"}</td>
                                <td className="py-3 pr-2 text-gray-600 font-sans max-w-[120px] break-words">{c.sanction || "—"}</td>
                                <td style={{ padding: "12px 0", textAlign: "right", verticalAlign: "middle", fontFamily: "sans-serif" }}>
                                  <span
                                    style={{
                                      ...getBadgeInlineStyle(c.progress),
                                      display: "inline-block",
                                      fontSize: "11px",
                                      fontWeight: 700,
                                      textTransform: "uppercase" as const,
                                      letterSpacing: "0.05em",
                                      whiteSpace: "nowrap",
                                      lineHeight: "1",
                                      verticalAlign: "middle",
                                    }}
                                  >
                                    {c.progress}
                                  </span>
                                </td>
                              </tr>
                            );
                          }) : (
                            <tr>
                              <td colSpan={9} className="py-8 text-center text-gray-500 text-sm font-sans italic">
                                No cases found for this period.
                              </td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>

                    {isLastPageChunk && !needsExtraPage && renderClosingBlock()}
                    
                    {renderPageFooter(index + 1, totalPagesCount)}
                  </div>
                );
              })}

              {needsExtraPage && (
                <div className="bg-white shadow-md print:shadow-none w-[297mm] h-[210mm] px-12 py-8 text-gray-800 font-serif relative" style={{ pageBreakAfter: 'always' }}>
                  {renderSmallHeader()}
                  {renderClosingBlock()}
                  {renderPageFooter(totalPagesCount, totalPagesCount)}
                </div>
              )}
            </div>"""

content = content[:report_ref_start] + new_report_ref_content + content[report_ref_end:]

with open('src/pages/SummaryReports.tsx', 'w') as f:
    f.write(content)
print("done")
